spring.data.mongodb.uri=mongodb://localhost:27017/cloudshare

server.servlet.context-path=/api/v1.0

spring.data.mongodb.auto-index-creation=true

spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.security.servlet.UserDetailsServiceAutoConfiguration

clerk.issuer=https://immense-oarfish-43.clerk.accounts.dev
clerk.jwks-url=https://immense-oarfish-43.clerk.accounts.dev/.well-known/jwks.json
clerk.webhook.secret=UJdPd0Z1K5alTo7GrGVF9315MGCHn53e

# file upload configuration
spring.servlet.multipart.max-file-size=5MB
spring.servlet.multipart.max-request-size=25MB

# Vnpay configuration 
vnpay.tmn-code=XACARHKN
vnpay.hash-secret=LUQIHILITPBAGG1GFPB69WYYZ7VSVQMO
vnpay.pay-url=https://sandbox.vnpayment.vn/paymentv2/vpcpay.html
vnpay.return-url=http://localhost:5173/payment/return
